### ISSUE TITLE
so sorry!!

### ISSUE THREAD

**Issue by Roomsaver** [yellows8/oot3dhax#15]
I'm having the same problems even after using the correct save file: N3DS_U_11272_8203.sav. 
It does the exact same thing as last time. Do I need the ropbin or otherapp and when I download that do I need to name it anything specific?

**Comment by ihaveamac** [comment]
I think you said you're on New 3DS 10.3.0-28U? that filename doesn't look right to me.

try N3DS_U_23552_usa_9221 because that's what I'm using on my system (same setup).

**Comment by Roomsaver** [comment]
I will do that right now and let you know

**Comment by Roomsaver** [comment]
Same thing as before :/

**Comment by Roomsaver** [comment]
I will try with a different otherapp and see if that works.

**Comment by Roomsaver** [comment]
Ian, are you running 2.1 or 2.5? Do you think running 2.1 might work and how I would go about installing that?

**Comment by ihaveamac** [comment]
I've used N3DS_U_23552_usa_9221.sav and POST5_U_23552_usa_9221.sav for cardid c2fe*. they are for New & Old 10.3.0-28U and both work fine for me.

the oot3dhax raw saveimages in Releases use *hax 2.5.

whenever it shows "The home menu ropbin is ready." and it crashes after that, I think that's because of an incorrect payload for the firmware version. could you double check your entire version?

**Comment by Roomsaver** [comment]
The version of my 3DS? New 10.3.0-28U

**Comment by Roomsaver** [comment]
The save is 23552 and the payload is 23552.

**Comment by Roomsaver** [comment]
Payload as in N3DS_U_23552_ua_9221.bin

**Comment by Roomsaver** [comment]
Well! It works now! I tried to see if the PowerSaves would work and, loandbehold, it did!
