### ISSUE TITLE
Stuck on *hax 2.6 

### ISSUE THREAD

**Issue by Lozy360** [yellows8/oot3dhax#63]
I'm on 11.0.0.33 and i used the new raw savefile for powersave and homebrew still loads on 2.6 and not 2.7 :(...

**Comment by yellows8** [comment]
Use sploit_installer to update.

@smealum didn't update otherapp.zip when \*hax 2.7 was "released".

**Comment by Lozy360** [comment]
When i run sploit_installer it just crashes to black/yellow screen ...

**Comment by yellows8** [comment]
NVM, forgot about that... :|

**Comment by Lozy360** [comment]
So my options are to use another hax or wait for it to get fixed?

**Comment by yellows8** [comment]
Yes.

**Comment by Lozy360** [comment]
R.I.P

**Comment by mmroos1983** [comment]
Mine also runs on 2.6 with 11.0. But how is this bad? Everything runs fine.

**Comment by Lozy360** [comment]
In order to use this:https://github.com/ihaveamac/9.6-dbgen-xmls
you need 2.7....
Btw i just installed basehax and updated my *hax :^)

**Comment by KaBombz** [comment]
I'm having this same issue, but also svdt hangs on a red screen along with a few other apps. supermysterychunkhax also freezes at a red screen - though I'm not sure whether or not that's due to *hax 2.6 or user error on my part, though I've tried everything. I was thinking about trying to compile my own savefile using the updated otherapp, but I've no idea how to go about that.
